//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanghui.OA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionInfo> ActionInfo { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<R_User_ActionInfo> R_User_ActionInfo { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SearchLog> SearchLog { get; set; }
        public virtual DbSet<SearchLogGroupBy> SearchLogGroupBy { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserExt> UserExt { get; set; }
        public virtual DbSet<WF_Instance> WF_Instance { get; set; }
        public virtual DbSet<WF_Step> WF_Step { get; set; }
        public virtual DbSet<WF_Temp> WF_Temp { get; set; }
    }
}
