//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanghui.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_Instance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WF_Instance()
        {
            this.WF_Step = new HashSet<WF_Step>();
        }
    
        public int ID { get; set; }
        public int WF_TempID { get; set; }
        public string InstanceName { get; set; }
        public System.Guid WFApplicationId { get; set; }
        public int SubmitBy { get; set; }
        public System.DateTime SubmitTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public short Status { get; set; }
        public short DelFlag { get; set; }
        public string Remark { get; set; }
        public string InstanceForm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_Step> WF_Step { get; set; }
        public virtual WF_Temp WF_Temp { get; set; }
    }
}
