//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanghui.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_Step
    {
        public int ID { get; set; }
        public int WF_InstanceID { get; set; }
        public string StepName { get; set; }
        public int ProcessBy { get; set; }
        public short Status { get; set; }
        public bool IsStartStep { get; set; }
        public bool IsEndStep { get; set; }
        public string Result { get; set; }
        public string Comment { get; set; }
        public System.DateTime SubmitTime { get; set; }
        public System.DateTime CheckTime { get; set; }
        public short DelFlag { get; set; }
        public string Remark { get; set; }
    
        public virtual WF_Instance WF_Instance { get; set; }
    }
}
